export const HARD_SKILLS = [
	'CAO',
	'Lean manufacturing',
	'Analyse multivariée',
	'Régression linéaire',
	'Prototypage',
	'Développement de flux de travail',
	'Compétences STEM',
	'Web : HTML, CSS, Javascript',
	'Traitement des paiements',
	'Systèmes de facturation automatisés',
	'Plateformes CRM',
	'Word',
	'Excel',
	'Outlook',
	'Powerpoint',
	'OneNote',
	'Access',
	'Google Drive',
	'Tableurs',
	'Email',
	'Présentations',
	'Diaporamas',
	'Gestion de bases de données',
	'Quickbooks',
	'Médias sociaux',
	'Dactylographie',
	'Graphisme',
	"Systèmes d'entreprise",
	'WPM',
	'Java',
	'PHP',
	'MySQL',
	'SQL',
	'C#',
	'JavaScript',
	'C++',
	'Python',
	'iOSSwift',
	'Ruby on Rails',
	'Analyse des données',
	'Programmation',
	'Rédaction technique',
	'Gestion de projet',
	'Service clientèle',
	'Gestion de la qualité',
	'Communication écrite et orale',
	'Compétences en informatique et logiciels',
	'Comptabilité et finance',
	'Résolution de problèmes',
	'Études de marché',
	'Négociation',
	'Leadership',
	'Conception graphique',
	'Droit',
	'Formation',
	'Logistique',
	'Stratégie',
	'Marketing',
	'SEO',
	'Gestion du temps',
	'Ressources humaines',
	'Business intelligence',
	'Connaissance des produits',
	'Analyse financière',
	'Outils analytiques',
	'Hardware Programmation',
	'Maintenance',
	'Comprendre les systèmes',
	'Vente',
	'Tests',
	'Conseil',
	'Écriture créative',
	'Statistiques',
	'Documentation',
	'Recrutement',
	'Psychologie',
	'Photographie',
	'Mentorat',
	'Automatisation',
	'Compréhension',
	'Assurance qualité',
	'Journalisme',
	'Langues',
	'Système',
	'Organisation',
	'Cultures',
	'Dessin',
	'Informatique',
	'Design',
	'Technologies',
	'Services',
	'Inventaire',
	'Mathematiques',
	'Musique',
	'Biologie',
	'System',
]

export const SOFT_SKILLS = [
	'Adaptabilité',
	'Autonomie',
	'Communication',
	'Compassion',
	'Créativité',
	'Détermination',
	'Empathie',
	'Flexibilité',
	'Gestion du stress',
	'Leadership',
	'Organisation',
	'Patience',
	'Perspicacité',
	'Proactivité',
	'Résolution de problèmes   ',
	'Sens des responsabilités',
	"Travail d'équipe",
	'Confiance en soi',
	'Diplomatie',
	'Ecoute active',
	'Esprit critique',
	'Esprit entrepreneurial',
	'Faire preuve d’initiative',
	'Force de persuasion',
	'Honnêteté',
	'Imagination',
	'Intuition',
	'Motivation',
	'Pensée stratégique',
	'Prise de décision',
	'Prise en charge',
	'Respect',
	'Responsabilité',
	'Résilience',
	'Souplesse',
	'Ténacité',
	'Écoute',
	'Efficacité',
	'Disponibilité',
	'Professionnalisme',
	'Capacités organisationnelles',
	'Optimisme',
	'Rigueur',
	'Souci du détail',
	'Autorité Discrétion',
	'Goût pour les challenges',
	'Curiosité /Discernement',
	'Engagement',
	'Enthousiasme',
	'Esprit analytique',
	'Ethique professionnelle',
	'Gestion du temps',
	'Grande capacite à apprendre',
	'Habiletés interpersonnelles',
	'Humour',
	'Inventivité',
	'Méthode',
	'Ouverture',
	'Polyvalence',
	'Productivité',
	'Qualités rédactionnelles',
	'Rigoureux',
	"Savoir s'adapter",
	'Volontariat',
	'Assiduitée',
	'Calme',
	'Charisme',
	'Clairvoyance',
	'Concentration',
	'Courage',
	'Dedication',
	'Diligence',
	'Dynamisme',
	'Enthousiasme',
	'Equilibre',
	'Expansivite',
	'Expression orale',
	'Extraversion',
	'Faculties d’adaptation',
	'Fiabilite',
	'Grande capacite a apprendre',
	'Habiletes sociales',
	'Impartialite',
	'Integrite',
	'Intelligence',
	'Loyalte',
	'Maturite',
	'Negociation',
	'Objectif',
	'Persistance',
	'Professionalisme',
	'Rapide',
	'Rationalisation',
	'Reconnaissance',
	'Reliability',
	'Respect',
	'Resilience',
	'Resultats',
	'Securite',
	'Sens',
	'Tact',
	'Technologiquement competent',
	'Tolerance',
	'Transparence',
	'Vision',
	'Agressivitè',
	'Analyse',
	'Attitude positive',
	'Autodiscipline',
	'Collaboration',
	'Comprehension',
	'Connaissance',
	'Creativite',
	'Decisions',
	'Desir',
	'Determine ',
	'Discipline',
	'Emotion',
	'Endurance',
	'Experiences',
	'Innovation',
	'Logique',
	'Neutrallty',
	'Perception',
	'Presentations',
	'Problem solving',
	'Reaction',
	'Relations',
	'Resourcefulness',
	'Strategiques',
	'Sympathic',
	'Technique',
	'Traitement',
	'Ambitieu',
	'Attention',
	'Clarte',
	'Competitives',
	'Conscience',
	'Consultant',
	'Cooperation',
	'Coherence',
	'Decision',
	'Detail',
	'Developpment',
	'Discretion',
	'Eco-friendly',
	'Efficiency',
	'Efficace',
	'Endurance',
	'Expert',
	'Exploitation',
	'Francais',
	'Genial',
	'Honnetete',
	'Imagination',
	' Independante',
	'Influence',
	'Interaction',
	'Intuition',
	'Leadership',
	'Liberte',
	'Managment',
	'Negotiation',
	'Original',
	'Passion',
	'Perfection',
	'Planification',
	'Poigne',
	'Politesse',
	'Precision',
	'Priorites',
	'Realiste',
	'Reflexions ',
	'Service',
]
