import Layout from 'components/layout/layout'
import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Recruiteer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<h1 style={{ textAlign: 'center' }}>Recruiteer.</h1>
			</Layout>
		</>
	)
}
